server:
  port: 8020
  shutdown: graceful
  servlet:
    context-path: /trade

spring:
  application:
    name: my-spring-trade
  profiles:
    active: dev
  config:
    import: "optional:consul:"
  datasource:
    url: jdbc:shardingsphere:classpath:sharding.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /trade/actuator/health
      config:
        enabled: true
        format: yaml
        watch:
          enabled: true
    openfeign:
      client:
        config:
          default:
            connect-timeout: 100
            read-timeout: 200
            logger-level: full
          my-spring-exchange:
            connect-timeout: 100
            read-timeout: 200

logging:
  level:
    com.emlyn.spring.trade.client: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: prod