server:
  port: 8001
  shutdown: graceful
  servlet:
    context-path: /trade

spring:
  application:
    name: my-spring-trade
  profiles:
    active: dev
  datasource:
    url: jdbc:shardingsphere:classpath:sharding.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:application.yaml?group=trade
      - nacos:common.json?group=trade

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: prod